version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: app
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - redis
    networks:
      - app_network
    ports:
      - "8080:8080"
    command: ["sh", "-c", "make migrate-up && make run"] # Runs Makefile command

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge